name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.20
main: FactionsPro\FactionMain
api: [3.0.0]
softdepend: ["AntiSpamPro"]
extensions: [sqlite3]
commands:
  t:
    description: utiliser /t help pour tous les paramètres
    permission: t.command
permissions:
  t.command:
    default: true
    description: "Autoriser l'utilisation de toutes les commandes de tribus"
